default_platform(:ios)

platform :ios do
  desc "Build and deploy iOS app to TestFlight"
  lane :beta do
    increment_build_number(
      xcodeproj: "ios/SharePlate.xcodeproj"
    )
    
    build_app(
      workspace: "ios/SharePlate.xcworkspace",
      scheme: "SharePlate",
      export_method: "app-store",
      clean: true,
      output_directory: "builds/ios",
      output_name: "SharePlate.ipa"
    )
    
    upload_to_testflight(
      skip_waiting_for_build_processing: true
    )
  end

  desc "Build and deploy iOS app to App Store"
  lane :release do
    increment_version_number(
      xcodeproj: "ios/SharePlate.xcodeproj"
    )
    
    build_app(
      workspace: "ios/SharePlate.xcworkspace",
      scheme: "SharePlate",
      export_method: "app-store",
      clean: true,
      output_directory: "builds/ios",
      output_name: "SharePlate.ipa"
    )
    
    upload_to_app_store(
      force: true,
      skip_metadata: true,
      skip_screenshots: true,
      skip_binary_upload: false
    )
  end
end

platform :android do
  desc "Build and deploy Android app to Play Store Beta track"
  lane :beta do
    increment_version_code(
      gradle_file_path: "android/app/build.gradle"
    )
    
    gradle(
      task: "clean bundleRelease",
      project_dir: "android/"
    )
    
    upload_to_play_store(
      track: "beta",
      aab: "android/app/build/outputs/bundle/release/app-release.aab"
    )
  end

  desc "Build and deploy Android app to Play Store"
  lane :release do
    increment_version_name(
      gradle_file_path: "android/app/build.gradle"
    )
    
    gradle(
      task: "clean bundleRelease",
      project_dir: "android/"
    )
    
    upload_to_play_store(
      track: "production",
      aab: "android/app/build/outputs/bundle/release/app-release.aab"
    )
  end
end 